[versions]
annotations = "23.0.0"
geantyref = "2.0.0"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }